# Charged-current $\nu_\mu$ interaction analysis with two detected protons (CC2p)

#Analysis of charged-current neutrino interactions. This repository is mainly divided into:

#- [`GeneratorAnalysis/`](https://github.com/afropapp13/CC1muAnalysis/tree/main/GeneratorAnalysis): contains scripts analysing events generated by different simulators.
#- [`CAFAnaAnalysis/`](https://github.com/afropapp13/CC1muAnalysis/tree/main/CAFAnaAnalysis): contains scripts analysing experiment data using the CAFAna framework.

#Plots generated through the scripts in both directories are placed under [`Figs/`](https://github.com/afropapp13/CC1muAnalysis/tree/main/Figs). 

me="$(whoami)"
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/Overlay
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/Overlay/Serial
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/Overlay/MEC
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/Overlay/MEC/Serial
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/InteBreakDown
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/InteBreakDown/PostFSI
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/InteBreakDown/PreFSI
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Cuts
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/InteBreakdown
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Serial
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Efficiency
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Matrices
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/NTargets
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/POT
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/Reinteraction
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/Detector
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/MCStat
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/Statistical
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/BinUncertainties
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/Unfolded
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/WienerSVDOverlay
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/FakeDataStudies
mkdir /pnfs/sbnd/persistent/users/${me}/cc2p/Figs/CAFAna/Uncertainties/FakeDataStudies/Combined

### Setting up

#If it is the first time working in this repository, you have to run

#```bash
#source setup.sh
#```

#to set up the correct feature branch of `sbnana` used in this codebase. Once this is done, you have to run

#```bash
#source activate.sh
#```

#to activate your local `sbnana` build every time you start a new terminal. This will also setup ROOT, so that you can run scripts in both `GeneratorAnalysis/` and `CAFAnaAnalysis/`. 
